#! /bin/sh
### BEGIN INIT INFO
# Provides: dencoder
# Required-Start:    $local_fs $syslog $remote_fs dbus
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dencoder, the distributed h264 encoding system
### END INIT INFO

. /lib/lsb/init-functions
NAME=dencoder.py
DAEMON=/usr/bin/dencoder.py

set -e

case "$1" in
  start)
    start-stop-daemon --start --quiet --pidfile /var/run/dnsmasq/$NAME.pid --exec $DAEMON > /dev/null || return 1
    ;;
  stop)
    pkill -TERM dencoder.py || true
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc "dencoder.py" "dencoder.py" && exit 0 || exit $?
    ;;
  *)
    # echo "Usage: $N {start|stop|restart|reload|force-reload|status}" >&2
    echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
